fix: provide default client_id and client_secret because they are not needed when using only jwt tokens (#76)
otherwise the gateway doesn't start when they are not defined
    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gatewayService': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'client_id' in value "${client_id}"