tests: fake sub instead of audience (#193)
altering the audience in the signed jwt doesn't trigger
the code path we want to test because we reject the token
ourselves even before validating it's cryptocraphic signature

altering the sub gives the correct test:
before (wrong test)
  17:24:09.778 [webflux-http-epoll-10] INFO  org.gridsuite.gateway.filters.TokenValidatorGlobalPreFilter - 401 Unauthorized, [td�t.app] Audience is not in the audiences white list
after (good test)
  17:25:15.185 [reactor-http-epoll-2] INFO  org.gridsuite.gateway.filters.TokenValidatorGlobalPreFilter - /v1/cases: 401 Unauthorized, The token cannot be trusted

and the catch block is really throwing
  com.nimbusds.jose.proc.BadJWSException: Signed JWT rejected: Invalid signature